### ISSUE TITLE
What is value `$CI_BUILD_TOKEN`

### ISSUE THREAD

**Issue by takat0-h0rikosh1** [JanMikes/gitlab-ci-push-to-gcr#1]
I hava a question.  
What is value `$CI_BUILD_TOKEN`.

https://github.com/JanMikes/gitlab-ci-push-to-gcr/blob/c9f09bedf9ba069d88c3c67c0461baba134386f2/.gitlab-ci.yml#L18

Will you please tell how to get value from GCP.

**Comment by JanMikes** [comment]
Hi, the `$CI_BUILD_TOKEN` is automatically added by gitlab itself. I just checked that it was renamed in 9.x version to `$CI_JOB_TOKEN`: https://docs.gitlab.com/ee/ci/variables/deprecated_variables.html

**Comment by takat0-h0rikosh1** [comment]
Ah, I understood. Everything is clear. Thank you.

**Comment by gonchik** [comment]
Just interesting why that did not mention in new docs
