### ISSUE TITLE
Error: Cannot perform an interactive login from a non TTY device

### ISSUE THREAD

**Issue by greg-witczak** [JanMikes/gitlab-ci-push-to-gcr#2]
For all of you fighting with error "Error: Cannot perform an interactive login from a non TTY device", solution was provided here: https://gitlab.com/gitlab-com/support-forum/issues/3524#note_150577883

long story short - if your branch is NOT protected, then your variable in GitLab should also be NOT protected. Otherwise (protected variable on non-protected branch) it will not work and you'll get docker login fail on abovementioned error message.

**Comment by JanMikes** [comment]
Hi, i have never faced this issue myself. I will add it to readme as issue someone might run into :-).

**Comment by mstrzele** [comment]
For ones struggling with login using environment variables only:

You can use `TF_TOKEN_app_terraform_io` or `TF_TOKEN_<hostname>`.

**Comment by ezargar377** [comment]
> For all of you fighting with error "Error: Cannot perform an interactive login from a non TTY device", solution was provided here: https://gitlab.com/gitlab-com/support-forum/issues/3524#note_150577883
> 
> long story short - if your branch is NOT protected, then your variable in GitLab should also be NOT protected. Otherwise (protected variable on non-protected branch) it will not work and you'll get docker login fail on abovementioned error message.

Bravo. very good

**Comment by IgnacioGarcia198** [comment]
that gitlab link is down.

**Comment by JanMikes** [comment]
Hi, you probably do not need the link to the original gitlab support forum. As i understood, the problem was the variable was not presented for the pipeline, because variable was protected running on a non-protected branch pipeline.
