### ISSUE TITLE
issue trying to push to gitlab ci registry

### ISSUE THREAD

**Issue by Gasperan** [JanMikes/gitlab-ci-push-to-gcr#6]
hi, I tried to use the build job and it is failing in this part:

```  script:
    - docker pull $GITLAB_IMAGE || true # Allows us to use --cache-from
    - docker build --cache-from $GITLAB_IMAGE -t $GITLAB_IMAGE:$CI_COMMIT_SHA .
    - docker push $GITLAB_IMAGE
```

if you build the image using the $CI_COMMIT_SHA value as tag, then you should push using same tag, otherwise you are going to receive the error:

`tag does not exist: [docker image]:latest`

I'm suggesting add the following in push command in gitlab-ci.yml file: 

```
    - docker push $GITLAB_IMAGE:$CI_COMMIT_SHA
```

I tried to create a branch to do a pull request but I don't have enough permissions.

**Comment by JanMikes** [comment]
Hi, thank you for letting me know. Referred [to this build](https://gitlab.com/lexisoft/gitlab-ci-push-to-gcr/-/jobs/152012067) (2 years ago) it worked, so it feels weird to me, but maybe just something changed :-)
